### ISSUE TITLE
Core node causes  circular reference error,  when context is set to filesystem

### ISSUE THREAD

**Issue by smcgann99** [pixelit-project/node-red-contrib-pixelit#20]
Core node causes the following error in node red debug, when context is set to filesystem as default. 

"Context 35ecb3fe.70a82c:43c26ad8e4dbc534 contains a circular reference that cannot be persisted"

**Comment by o0shojo0o** [comment]
NodeRed makes problems if you want to store more complex objects serialized in the file system. 
like here e.g. https://github.com/pixelit-project/node-red-contrib-pixelit/blob/3a83e3206ae82bdf99bbea23b5226e8e7dd406b2/pixelit/core.js#L138
But I haven't found a solution for this yet.
