### ISSUE TITLE
lighting adjustment

### ISSUE THREAD

**Issue by maverik80** [pixelit-project/node-red-contrib-pixelit#21]
good morning and congratulations on the project you are carrying out, very nice. I am a beginner and I am untangling myself with an 8x32 led panel and in many things I have succeeded but I cannot create a flow that manages the brightness for me, by chance someone has an example of how I can manage it manually and how to integrate it in the home assistant?

thanks in advance for the availability

**Comment by rafalw1277** [comment]
I have the same problem, someone may have solved it
