### ISSUE TITLE
Pixelit makes NodeRED crashing with latest versions

### ISSUE THREAD

**Issue by GregS1000RR** [pixelit-project/node-red-contrib-pixelit#25]
Hi,
Since latest update from HassIO, Node-Red is crashing while trying to launch Pixelit.core

See bellow log output

PS: If I remove this specific lib from "package.json", then NodeRed starts

Can you please have a look.
Thank you

` Add-on version: 13.3.1
 You are running the latest version of this add-on.
 System: Home Assistant OS 8.4  (armv7 / raspberrypi4)
 Home Assistant Core: 2022.8.4
 Home Assistant Supervisor: 2022.08.3

Welcome to Node-RED
===================
15 Aug 20:26:34 - [info] Node-RED version: v3.0.2
15 Aug 20:26:34 - [info] Node.js  version: v16.16.0
15 Aug 20:26:34 - [info] Linux 5.15.32-v7l arm LE
15 Aug 20:26:35 - [info] Loading palette nodes
rpi_gpio_s32.node driver V1.23 (c) Ocean iiot2k@gmail.com
15 Aug 20:26:42 - [info] Dashboard version 3.1.7 started at /endpoint/ui
15 Aug 20:26:43 - [info] Settings file  : /etc/node-red/config.js
15 Aug 20:26:43 - [info] Context store  : 'default' [module=memory]
15 Aug 20:26:43 - [info] User directory : /config/node-red/
15 Aug 20:26:43 - [warn] Projects disabled : editorTheme.projects.enabled=false
15 Aug 20:26:43 - [info] Flows file     : /config/node-red/flows.json
15 Aug 20:26:43 - [info] Server now running at http://127.0.0.1:46836/
15 Aug 20:26:43 - [info] Starting flows
15 Aug 20:26:44 - [info] Started flows
15 Aug 20:26:44 - [info] [mqtt-broker:HASSIO] Connected to broker: mqtt://127.0.0.1:1883
15 Aug 20:26:45 - [red] Uncaught Exception:
15 Aug 20:26:45 - [error] SyntaxError: Unexpected token , in JSON at position 183
    at JSON.parse (<anonymous>)
    at createScreenJson (/config/node-red/node_modules/node-red-contrib-pixelit/pixelit/core.js:243:48)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at core._inputCallback (/config/node-red/node_modules/node-red-contrib-pixelit/pixelit/core.js:145:37)
[20:26:45] WARNING: Node-RED crashed, halting add-on
[20:26:45] INFO: Node-RED stoped, restarting...
s6-rc: info: service legacy-services: stopping
[20:26:45] INFO: Node-RED stoped, restarting...
s6-svwait: fatal: supervisor died
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
`

**Comment by o0shojo0o** [comment]
There is a bitmap array error in your flow, did you enter it manually or by API ID?

**Comment by GregS1000RR** [comment]
To start playing with this nice project, I used the example flow, and added  (copy/past) some nodes to play with.

The "strange" thing, it worked until last update.

Attached the Flow
[Pixelit-tst.json.txt](https://github.com/pixelit-project/node-red-contrib-pixelit/files/9348053/Pixelit-tst.json.txt)

**Comment by o0shojo0o** [comment]
I found the error, you used the bitmap node instead of the required bitmap animation. 
![image](https://user-images.githubusercontent.com/19333515/184825419-e857538b-caf1-4c47-96de-87c81306ee96.png)
But I will still install something that does not immediately support everything with this error

**Comment by GregS1000RR** [comment]
Hi Dennis,

Thank you for your fast response.

Indeed, I removed the bitmap node, and it worked fine

Thank you
Best regards

Gregory

Le mar. 16 août 2022 à 09:45, Dennis Rathjen ***@***.***> a
écrit :
